### ISSUE TITLE
Cards on PyAnsys docs don't point to stable version

### ISSUE THREAD

**Issue by klmcadams** [ansys/pyansys#419]
https://docs.pyansys.com/version/stable/

If you click PyMechanical from the link above, it goes to https://mechanical.docs.pyansys.com/version/0.8/ instead of https://mechanical.docs.pyansys.com/version/stable

This happens for all of the cards on this page

**Comment by RobPasMue** [comment]
Not an issue - it is expected behavior.

The released version of our PyAnsys docs (latest one is 2023.2) is pointing to the documentation version specific for each dependency we are pinning. For example, if package X is being pinned down at version 2.2 we are redirecting to its 2.2 version documentation, and not to its latest stable docs.

If you want to access the latest stable docs for package X you can do that from the dev version of the PyAnsys documentation: https://docs.pyansys.com/version/dev/index.html

**Comment by PipKat** [comment]
@RobPasMue It might be helpful to explain this on the page: https://docs.pyansys.com/version/stable/

I can see how it could be quite confusing and what would lead @klmcadams to open this issue! If you would like me to work in the explanation provided above, let me know!

**Comment by klmcadams** [comment]
@PipKat If you don't mind working in the explanation, that would be great! I think it would be helpful as well

**Comment by RobPasMue** [comment]
I am working on making it more intuitive. For the PyAnsys docs we will now point to version/dev instead of version/stable by default.

This will solve these issues.

**Comment by PipKat** [comment]
@Roberto Will the default for all Pyansys docs now point to version/dev instead of version/stable by default or just for this page? I ask because the answer could possibly affect lots of blurbs about using the dropdown in the header to select a doc version. The doc link for the repo takes the user to the stable version--so will this still be true is really my question.
Copy @klmcadams

**Comment by RobPasMue** [comment]
It will only be for this page. We have no mention whatsoever to the dropdown in these docs if I remember properly. The doc link of this repo will now take users to the dev docs by default.

**Comment by RobPasMue** [comment]
Problem solved. Check out https://docs.pyansys.com/
